### ISSUE TITLE
更新了组织介绍

### ISSUE THREAD

**Issue by ohto-ai** [SSSS-ODDEYE/.github#1]
@beiklive 

![image](https://user-images.githubusercontent.com/46275725/196652672-8d7f7e28-ff9c-461f-b95f-a9ceef2fa335.png)

**Comment by ohto-ai** [comment]
![image](https://user-images.githubusercontent.com/46275725/197098940-9425b1c8-8b82-4a1e-bbfe-d6691247bf1b.png)

更新了contribution 蛇形图

**Comment by beiklive** [comment]
@Ohto-Ai  帮我主页也更新一下:smile

**Comment by ohto-ai** [comment]
> @Ohto-Ai 帮我主页也更新一下:smile

更新什么

**Comment by ohto-ai** [comment]
> > @Ohto-Ai 帮我主页也更新一下:smile
> 
> 更新什么

你主页不是已经有了吗

**Comment by ohto-ai** [comment]
![](https://raw.githubusercontent.com/SSSS-ODDEYE/.github/master/assets/github-contribution-grid-snake-beiklive.svg)

引用这个仓库的文件吧
```markdown
![](https://raw.githubusercontent.com/SSSS-ODDEYE/.github/master/assets/github-contribution-grid-snake-beiklive.svg)
```

**Comment by beiklive** [comment]
> > > @Ohto-Ai 帮我主页也更新一下:smile
> > 
> > 
> > 更新什么
> 
> 你主页不是已经有了吗

主页那个是假的

**Comment by beiklive** [comment]
改好了

**Comment by ohto-ai** [comment]
> 改好了

ok

**Comment by Ohto-Ai** [comment]
![Write Everywhere Read Nowhere][github-sub-title:img]


[github-sub-title:img]: https://readme-typing-svg.herokuapp.com?font=Segoe+Script&center=true&lines=Write+Everywhere%2C;Read+Nowhere.

**Comment by ohto-ai** [comment]
![](https://readme-typing-svg.herokuapp.com?font=Segoe+Script&center=true&lines=第一，我不叫喂，我叫楚雨荨;第二，绝不漏判任何一件坏事;第三，还是tm公平)

**Comment by ohto-ai** [comment]
@beiklive

**Comment by beiklive** [comment]
> Reference

@Ohto-Ai

**Comment by ohto-ai** [comment]
> > Reference
> 
> @Ohto-Ai

@beiklive
